### PR TITLE
Fix wavefront persist

### LINKED ISSUE #287: Persist Telemetry is broken in the Wavefront sink
With the switch to padding via consuming aggregator the Wavefront sink has broken its persist metrics. These are no longer persisted across flush windows. This must be corrected.

### PR DESCRIPTION
**Pull request by blt**
This commit ensures that we keep our persist telemetry around
for the next flush window. Much thanks to Tom Santero for the
simple fix idea.

This commit fixes #287

### CODE REVIEW

File: src/sink/wavefront.rs [hunk 1]
```diff
@@ -247,7 +251,13 @@ impl Wavefront {
 
         let mut tag_buf = String::with_capacity(1_024);
         let aggrs = mem::replace(&mut self.aggrs, Buckets::default());
-        for value in padding(aggrs.into_iter().filter(|x| x.is_zeroed()), self.bin_width) {
+        for value in
+            padding(aggrs.into_iter().filter(|x| x.is_zeroed()), self.bin_width)
```
Comment (pulltab) [inline src/sink/wavefront.rs]: Can you unpack this a bit for me?

Comment (blt) [inline src/sink/wavefront.rs]: Sure thing. 

`aggrs.into_iter()` converts `aggrs` into a iterator, meaning `aggrs` is no longer a valid reference and we'll be given an iterator that owns the `Telemetry` formerly in `aggrs`. 

`.filter(|x| x.is_zeroed()` removes any zero valued `Telemetry` from the iterator stream. We do this in preparation for padding. 

`padding` is a function which returns a `Padding` iterator, one that adds zeros according to the procedure outlined here: https://github.com/postmates/cernan/issues/247#issuecomment-314837565 We previously removed all zero-values from the stream to avoid complicating the padding iterator. It's guaranteed that there are no zeros to have to cope with.

File: src/sink/wavefront.rs [hunk 2]
```diff
@@ -247,7 +251,13 @@ impl Wavefront {
...
+        {
+            if value.persist {
+                let new_val = value.clone();
+                self.aggrs.add(new_val.timestamp(value.timestamp + 1));
```
Comment (pulltab) [inline src/sink/wavefront.rs]: Oh..this is self.aggrs.

Comment (blt) [inline src/sink/wavefront.rs]: It is. `self.aggrs` is different from `aggrs` which got consumed previously. When we do `mem::replace` above what we're doing is allocating a new `Bucket`, sticking it into the reference at `self.aggrs` and returning `aggrs`. 

That is, `self.aggrs` is a pointer into the `Self` == `Wavefront` struct and `aggrs` is a locally scoped heap object.
